"""add week_count

Revision ID: 407c4a4b5847
Revises: 1b02002bd815
Create Date: 2026-08-01 14:24:02.610049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407c4a4b5847'
down_revision: Union[str, None] = '1b02002bd815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('week_count', sa.Integer(), server_default='0', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'week_count')
    # ### end Alembic commands ###
