"""add winners count

Revision ID: 6c3c7ebc4e57
Revises: 081313cf21c6
Create Date: 2026-08-01 13:07:11.735478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c3c7ebc4e57'
down_revision: Union[str, None] = '081313cf21c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giveaways', sa.Column('winners_count', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giveaways', 'winners_count')
    # ### end Alembic commands ###
